### ISSUE TITLE
JavaScriptEngine是否可以考虑迁移到DuktapeJava引擎

### ISSUE THREAD

**Issue by gubaojian** [Clouda-team/boostui-native#2]
JavaScript引擎地址： https://github.com/gubaojian/DuktapeJava  
我的QQ： 787277208   有兴趣的话，我们联合开发一下，搞一个android版本的react-native

**Comment by zhangyuanwei** [comment]
目前我们的Js引擎采用的是WebView自带的Js引擎。基于多方面的考虑，暂时还没有使用其他引擎的打算。感谢您的关注。
